FROM oven/bun:1.3-alpine
WORKDIR /app
COPY bunfig.toml ./
COPY package.json bun.lock ./
COPY tsconfig.json tsconfig.base.json ./
COPY packages/shared/package.json packages/shared/
COPY packages/bots/package.json packages/bots/
COPY packages/bots/tsconfig.json packages/bots/
RUN bun install --backend=symlink
COPY packages/bots/src packages/bots/src
COPY packages/shared/src packages/shared/src
CMD ["bun", "run", "packages/bots/src/spawn.ts"]
