FROM oven/bun:1

WORKDIR /app

COPY package.json bun.lock ./
COPY tsconfig.json tsconfig.base.json ./
COPY packages/client/package.json packages/client/package.json
COPY packages/server/package.json packages/server/package.json
COPY packages/shared/package.json packages/shared/package.json

RUN bun install

CMD ["bun", "run", "dev"]
